# Generated by Django 3.2.16 on 2022-10-31 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_comments_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='featuered_image',
            new_name='featured_image',
        ),
    ]
